version: '3'

networks:
  backend:
    driver: overlay

services:
  scrapyd:
    build: ./onbuild
    image: scrapyd-onbuild
    ports:
      - "127.0.0.1:6800:6800"
    volumes:
      - ./scrapyd:/var/lib/scrapyd
    restart: always
    networks:
      - backend

  scrapy:
    build: ./onbuild
    image: scrapyd-onbuild
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./scrapy:/data
    working_dir: /data
    restart: always
    networks:
      - backend

  scrapyrt:
    build: ./onbuild
    image: scrapyd-onbuild
    command: scrapyrt -i 0.0.0.0 -p 9080
    ports:
      - "127.0.0.1:9080:9080"
    volumes:
      - ./scrapyrt:/data
    working_dir: /data
    restart: always
    networks:
      - backend